print("Hello World!!!")
print ("Ovo je nova izmjena")
print ("Ovo je treca izmjena")
print ("Ovo bi se trebalo spojiti sa glavnom granom")
print ("27.11.2022., pokusaj dodavanja izmjena na git lokalno")
